services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      FRONTEND_ORIGIN: https://apps.vajapravin.me
    restart: unless-stopped
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      API_BASE: https://apps.vajapravin.me/api
    volumes:
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
